#!/usr/bin/env sh

## TODO: Portability? Workaround the fact that nimrod breaks
## if you try to run it from a symlink
if test -L $(which nimrod); then
   NIMROD=$(readlink $(which nimrod))
else
   NIMROD=nimrod
fi;

## Compile the files
${NIMROD} compile -c --noMain --opt:speed src/*.nim

## Move from nimcache to src
cd src/nimcache
for filename in *.c; do mv "${filename}" "../nimrod_${filename}"; done
cd ../../

## Delete the cache dir
rm -rf src/nimcache

