#!/usr/bin/env sh

## Compile the files
/usr/local/Cellar/nimrod/0.9.2/libexec/bin/nimrod compile -c --noMain src/*.nim

## Move from nimcache to src
cd src/nimcache
for filename in *.c; do mv "${filename}" "../nimrod_${filename}"; done
cd ../../

## Delete the cache dir
rm -rf src/nimcache

